import{S as f,N as g,a as L,P as B,b as q}from"./assets/vendor-5ZdD33SK.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const n of document.querySelectorAll('link[rel="modulepreload"]'))r(n);new MutationObserver(n=>{for(const s of n)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function o(n){const s={};return n.integrity&&(s.integrity=n.integrity),n.referrerPolicy&&(s.referrerPolicy=n.referrerPolicy),n.crossOrigin==="use-credentials"?s.credentials="include":n.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(n){if(n.ep)return;n.ep=!0;const s=o(n);fetch(n.href,s)}})();const M=document.querySelectorAll(".mobile-menu-btn"),P=document.querySelector(".mobile-menu");console.log("object");M.forEach(e=>e.addEventListener("click",C));function C(){document.body.classList.toggle("no-scroll"),P.classList.toggle("is-open")}const A=document.querySelector(".mobile-nav");A.addEventListener("click",$);function $(e){e.target.className==="nav-link"&&(console.log(e.target),C())}new f(".hero-main-slider",{modules:[g],loop:!1,speed:300,slidesPerView:1,keyboard:{enabled:!0,onlyInViewport:!0},watchOverflow:!0,navigation:{nextEl:".swiper-button-hero-next",prevEl:".swiper-button-hero-prev"},breakpoints:{768:{slidesPerView:1},1440:{slidesPerView:1}}});const E="https://books-backend.p.goit.global/books";async function h(){try{return(await L.get(`${E}/top-books`)).data.flatMap(r=>r.books).filter((r,n,s)=>n===s.findIndex(l=>l.title===r.title&&l.author===r.author))}catch(e){console.error("Error fetching top books:",e)}}async function x(e){try{return(await L.get(`${E}/category?category=${encodeURIComponent(e)}`)).data.filter((r,n,s)=>n===s.findIndex(l=>l.title===r.title&&l.author===r.author))}catch(t){console.error("Error fetching books by category:",t)}}const N=document.querySelectorAll(".category-item"),S=document.querySelector(".category-select"),b=document.querySelector(".books"),_=document.querySelector(".loader"),d=document.querySelector(".show-more-btn"),V=document.querySelector("#books-count");function y(){_.classList.remove("hidden")}function k(){_.classList.add("hidden")}function w(){d.classList.remove("hidden")}function u(){d.classList.add("hidden")}function I(e){return e.toLowerCase().split(" ").map(t=>t.charAt(0).toUpperCase()+t.slice(1)).join(" ")}let i=[],c=0,v=window.innerWidth<768?10:24;const O=4;function p(e){const t=Math.min(c+e,i.length),o=i.slice(c,t);b.insertAdjacentHTML("beforeend",F(o)),c=t,V.textContent=`Showing ${t} of ${i.length}`,c>=i.length&&u()}u();y();h().then(e=>{i=e,p(v),i.length>c&&w()}).finally(()=>{k()});d.addEventListener("click",()=>{p(O);const t=document.querySelector(".books li").getBoundingClientRect().height;window.scrollBy({top:t*1,behavior:"smooth"}),d.blur()});function F(e){return e.map(t=>`
<li class="book-item">
  <img class="item-image" src="${t.book_image}" alt="${t.title}" />
  
  <div class="book-content">
    <div class="book-info">
      <div class="text-group">
        <h3 class="item-title">${I(t.title)}</h3>
        <p class="item-author">${t.author}</p>
      </div>
      <p class="item-price">$${t.price}</p>
    </div>
  </div>

  <button class="btn">Learn More</button>
</li>`).join("")}S.addEventListener("change",()=>{const e=S.value;u(),y(),b.innerHTML="",c=0,(e==="All categories"?h:()=>x(e))().then(o=>{i=o,p(v),i.length>c&&w()}).finally(()=>{k()})});N.forEach(e=>{e.addEventListener("click",()=>{const t=e.dataset.category;u(),y(),b.innerHTML="",c=0,(t==="All categories"?h:()=>x(t))().then(r=>{i=r,p(v),i.length>c&&w()}).finally(()=>{k()})})});let a=null;function T(e){a&&m();const o=document.querySelector("#book-modal-template").content.cloneNode(!0);o.querySelector(".book-modal__image").src=e.image||"",o.querySelector(".book-modal__image").alt=e.title||"Book Cover",o.querySelector(".book-modal__title").textContent=e.title||"",o.querySelector(".book-modal__author").textContent=e.author||"",o.querySelector(".book-modal__price").textContent=e.price||"",o.querySelector(".book-modal__description").textContent=e.description||"",o.querySelector(".book-modal__shipping").textContent=e.shipping||"",o.querySelector(".book-modal__returns").textContent=e.returns||"",a=o,document.body.appendChild(a);const r=document.querySelector(".book-modal-backdrop");r.addEventListener("click",j),r.querySelector('[data-action="close-modal"]').addEventListener("click",m),H(r)}function m(){const e=document.querySelector(".book-modal-backdrop");e&&e.remove(),a=null}function j(e){e.target.classList.contains("book-modal-backdrop")&&m()}function H(e){const t=e.querySelectorAll(".accordion");t.forEach(o=>{o.addEventListener("click",()=>{t.forEach(n=>{n!==o&&(n.classList.remove("active"),n.nextElementSibling.classList.remove("open"))}),o.classList.toggle("active"),o.nextElementSibling.classList.toggle("open")})})}new f(".swiper",{modules:[g,B,q],speed:350,slidesPerView:"auto",spaceBetween:16,keyboard:{enabled:!0,onlyInViewport:!0},watchOverflow:!0,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},pagination:{el:".feedback .swiper-pagination",type:"bullets",clickable:!0,bulletClass:"custom-bullet",bulletActiveClass:"custom-bullet-active"},breakpoints:{768:{slidesPerView:"auto",spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}}});new f(".swiper-events",{modules:[g,B,q],wrapperClass:"swiper-wrapper-events",slideClass:"swiper-slide-events",speed:350,slidesPerView:"auto",spaceBetween:16,watchOverflow:!0,navigation:{nextEl:".swiper-events-button-next",prevEl:".swiper-events-button-prev"},pagination:{el:".slider-controls .swiper-pagination",clickable:!0,bulletClass:"custom-bullet",bulletActiveClass:"custom-bullet-active"},breakpoints:{768:{slidesPerView:2,spaceBetween:24},1440:{slidesPerView:3,spaceBetween:24}}});document.addEventListener("click",e=>{const t=e.target.closest(".book-card");if(!t)return;t.dataset.bookId,T({title:"The Great Gatsby",author:"F. Scott Fitzgerald",price:"$9.99",image:"https://example.com/gatsby.jpg",description:"A novel set in the roaring twenties...",shipping:"Ships in 2–4 days",returns:"14-day return policy"})});
//# sourceMappingURL=index.js.map
